language: ruby
rvm:
- 3.0.5

before_script:
 - chmod +x ./_scripts/build-jekyll.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
#script: bundle exec jekyll build --verbose --trace
script: /bin/sh ./_scripts/build-jekyll.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
